(function () {
  const starterPlayers = [
    {
      id: "ali-dia",
      name: "Ali Dia",
      rarity: "Starter",
      speed: 4,
      shot: 3,
      dribble: 3,
      defense: 2,
      special: "Mystery Trialist",
      unlocked: true,
    },
    {
      id: "massimo-taibi",
      name: "Massimo Taibi",
      rarity: "Starter",
      speed: 3,
      shot: 2,
      dribble: 3,
      defense: 5,
      special: "Keeper Chaos",
      unlocked: true,
    },
    {
      id: "bebeto",
      name: "Bebeto",
      rarity: "Starter",
      speed: 5,
      shot: 3,
      dribble: 4,
      defense: 4,
      special: "Emergency Right Back",
      unlocked: true,
    },
    {
      id: "julien-faubert",
      name: "Julien Faubert",
      rarity: "Starter",
      speed: 5,
      shot: 3,
      dribble: 4,
      defense: 3,
      special: "Surprise Loan Sprint",
      unlocked: true,
    },
    {
      id: "joey-beauchamp",
      name: "Joey Beauchamp",
      rarity: "Starter",
      speed: 5,
      shot: 3,
      dribble: 4,
      defense: 3,
      special: "Left Wing Gamble",
      unlocked: true,
    },
    {
      id: "winston-bogarde",
      name: "Winston Bogarde",
      rarity: "Starter",
      speed: 3,
      shot: 2,
      dribble: 3,
      defense: 6,
      special: "Contract Wall",
      unlocked: true,
    },
    {
      id: "harry-maguire",
      name: "Harry Maguire",
      rarity: "Starter",
      speed: 3,
      shot: 3,
      dribble: 3,
      defense: 6,
      special: "Headed Clearance",
      unlocked: true,
    },
    {
      id: "joe-willock",
      name: "Joe Willock",
      rarity: "Starter",
      speed: 5,
      shot: 4,
      dribble: 5,
      defense: 3,
      special: "Late Box Run",
      unlocked: true,
    },
    {
      id: "tomas-brolin",
      name: "Tomas Brolin",
      rarity: "Starter",
      speed: 4,
      shot: 4,
      dribble: 4,
      defense: 4,
      special: "Old-School Engine",
      unlocked: true,
    },
    {
      id: "alberto-moreno",
      name: "Alberto Moreno",
      rarity: "Starter",
      speed: 6,
      shot: 3,
      dribble: 4,
      defense: 4,
      special: "Wild Overlap",
      unlocked: true,
    },
    {
      id: "loris-karius",
      name: "Loris Karius",
      rarity: "Starter",
      speed: 3,
      shot: 2,
      dribble: 3,
      defense: 5,
      special: "Cup Final Reflex",
      unlocked: true,
    },
    {
      id: "titus-bramble",
      name: "Titus Bramble",
      rarity: "Starter",
      speed: 3,
      shot: 2,
      dribble: 3,
      defense: 6,
      special: "Scramble Block",
      unlocked: true,
    },
    {
      id: "andre-santos",
      name: "Andre Santos",
      rarity: "Starter",
      speed: 5,
      shot: 3,
      dribble: 4,
      defense: 4,
      special: "Loose Left Side",
      unlocked: true,
    },
    {
      id: "bebe",
      name: "Bebe",
      rarity: "Starter",
      speed: 5,
      shot: 3,
      dribble: 4,
      defense: 2,
      special: "Wildcard Cross",
      unlocked: true,
    },
  ];

  const legendCards = [
    {
      id: "lionel-messi",
      name: "Lionel Messi",
      rarity: "Legendary",
      speed: 8,
      shot: 9,
      dribble: 10,
      defense: 4,
      special: "Magic Dribble",
      unlocked: false,
    },
    {
      id: "lamine-yamal",
      name: "Lamine Yamal",
      rarity: "Legendary",
      speed: 9,
      shot: 8,
      dribble: 9,
      defense: 4,
      special: "Wonderkid Burst",
      unlocked: false,
    },
    {
      id: "neymar",
      name: "Neymar",
      rarity: "Legendary",
      speed: 8,
      shot: 8,
      dribble: 10,
      defense: 3,
      special: "Rainbow Flick",
      unlocked: false,
    },
    {
      id: "luis-suarez",
      name: "Luis Suárez",
      rarity: "Legendary",
      speed: 7,
      shot: 9,
      dribble: 8,
      defense: 5,
      special: "Clutch Finish",
      unlocked: false,
    },
    {
      id: "gareth-bale",
      name: "Gareth Bale",
      rarity: "Legendary",
      speed: 9,
      shot: 9,
      dribble: 7,
      defense: 5,
      special: "Long Sprint Rocket",
      unlocked: false,
    },
    {
      id: "ronaldinho",
      name: "Ronaldinho",
      rarity: "Legendary",
      speed: 8,
      shot: 8,
      dribble: 10,
      defense: 4,
      special: "No-Look Trick",
      unlocked: false,
    },
    {
      id: "diego-maradona",
      name: "Diego Maradona",
      rarity: "Legendary",
      speed: 8,
      shot: 9,
      dribble: 10,
      defense: 5,
      special: "Golden Slalom",
      unlocked: false,
    },
    {
      id: "iker-casillas",
      name: "Iker Casillas",
      rarity: "Legendary",
      speed: 5,
      shot: 2,
      dribble: 5,
      defense: 10,
      special: "Lightning Save",
      unlocked: false,
    },
    {
      id: "kylian-mbappe",
      name: "Kylian Mbappé",
      rarity: "Legendary",
      speed: 10,
      shot: 9,
      dribble: 9,
      defense: 4,
      special: "Turbo Sprint",
      unlocked: false,
    },
    {
      id: "gianluigi-buffon",
      name: "Gianluigi Buffon",
      rarity: "Legendary",
      speed: 4,
      shot: 2,
      dribble: 4,
      defense: 10,
      special: "Wall Save",
      unlocked: false,
    },
    {
      id: "vinicius-junior",
      name: "Vinícius Junior",
      rarity: "Legendary",
      speed: 10,
      shot: 8,
      dribble: 10,
      defense: 4,
      special: "Wing Blur",
      unlocked: false,
    },
    {
      id: "cristiano-ronaldo",
      name: "Cristiano Ronaldo",
      rarity: "Legendary",
      speed: 9,
      shot: 9,
      dribble: 8,
      defense: 5,
      special: "Siu Finish",
      unlocked: false,
    },
    {
      id: "david-raya",
      name: "David Raya",
      rarity: "Legendary",
      speed: 6,
      shot: 2,
      dribble: 5,
      defense: 9,
      special: "Quick Keeper Hands",
      unlocked: false,
    },
    {
      id: "joan-garcia",
      name: "Joan Garcia",
      rarity: "Epic",
      speed: 6,
      shot: 2,
      dribble: 5,
      defense: 9,
      special: "Box Command",
      unlocked: false,
    },
    {
      id: "pele",
      name: "Pelé",
      rarity: "Legendary",
      speed: 9,
      shot: 10,
      dribble: 10,
      defense: 5,
      special: "Perfect Finish",
      unlocked: false,
    },
    {
      id: "franz-beckenbauer",
      name: "Franz Beckenbauer",
      rarity: "Legendary",
      speed: 7,
      shot: 7,
      dribble: 8,
      defense: 10,
      special: "Sweeper Captain",
      unlocked: false,
    },
    {
      id: "jamie-carragher",
      name: "Jamie Carragher",
      rarity: "Epic",
      speed: 5,
      shot: 3,
      dribble: 4,
      defense: 9,
      special: "Last-Ditch Block",
      unlocked: false,
    },
    {
      id: "pedri",
      name: "Pedri",
      rarity: "Legendary",
      speed: 7,
      shot: 7,
      dribble: 9,
      defense: 7,
      special: "Midfield Glide",
      unlocked: false,
    },
    {
      id: "jude-bellingham",
      name: "Jude Bellingham",
      rarity: "Legendary",
      speed: 8,
      shot: 8,
      dribble: 8,
      defense: 8,
      special: "Late Box Run",
      unlocked: false,
    },
    {
      id: "luis-figo",
      name: "Luis Figo",
      rarity: "Legendary",
      speed: 8,
      shot: 8,
      dribble: 9,
      defense: 5,
      special: "Creative Maestro",
      unlocked: false,
    },
    {
      id: "harry-kane",
      name: "Harry Kane",
      rarity: "Legendary",
      speed: 7,
      shot: 10,
      dribble: 8,
      defense: 5,
      special: "Haunted Finish",
      unlocked: false,
    },
    {
      id: "luka-modric",
      name: "Luka Modric",
      rarity: "Legendary",
      speed: 8,
      shot: 8,
      dribble: 10,
      defense: 7,
      special: "Ghost Pass",
      unlocked: false,
    },
    {
      id: "virgil-van-dijk",
      name: "Virgil van Dijk",
      rarity: "Legendary",
      speed: 8,
      shot: 5,
      dribble: 7,
      defense: 10,
      special: "Graveyard Wall",
      unlocked: false,
    },
    {
      id: "achraf-hakimi",
      name: "Achraf Hakimi",
      rarity: "Legendary",
      speed: 10,
      shot: 7,
      dribble: 8,
      defense: 8,
      special: "Midnight Overlap",
      unlocked: false,
    },
    {
      id: "alphonso-davies",
      name: "Alphonso Davies",
      rarity: "Legendary",
      speed: 10,
      shot: 7,
      dribble: 8,
      defense: 8,
      special: "Shadow Sprint",
      unlocked: false,
    },
    {
      id: "declan-rice",
      name: "Declan Rice",
      rarity: "Legendary",
      speed: 7,
      shot: 7,
      dribble: 8,
      defense: 9,
      special: "Phantom Shield",
      unlocked: false,
    },
    {
      id: "sergio-ramos",
      name: "Sergio Ramos",
      rarity: "Legendary",
      speed: 7,
      shot: 7,
      dribble: 7,
      defense: 10,
      special: "Cursed Header",
      unlocked: false,
    },
    {
      id: "rio-ferdinand",
      name: "Rio Ferdinand",
      rarity: "Legendary",
      speed: 7,
      shot: 5,
      dribble: 7,
      defense: 10,
      special: "Iron Back Line",
      unlocked: false,
    },
    {
      id: "reece-james",
      name: "Reece James",
      rarity: "Legendary",
      speed: 8,
      shot: 7,
      dribble: 8,
      defense: 8,
      special: "Power Overlap",
      unlocked: false,
    },
    {
      id: "william",
      name: "William",
      rarity: "Legendary",
      speed: 9,
      shot: 8,
      dribble: 9,
      defense: 4,
      special: "Lantern Cutback",
      unlocked: false,
    },
    {
      id: "zinedine-zidane",
      name: "Zinedine Zidane",
      rarity: "Legendary",
      speed: 8,
      shot: 9,
      dribble: 10,
      defense: 6,
      special: "Moonlit Roulette",
      unlocked: false,
    },
    {
      id: "federico-dimarco",
      name: "Federico Dimarco",
      rarity: "Legendary",
      speed: 8,
      shot: 7,
      dribble: 8,
      defense: 9,
      special: "Legendary Cross",
      unlocked: false,
    },
    {
      id: "paolo-maldini",
      name: "Paolo Maldini",
      rarity: "Legendary",
      speed: 8,
      shot: 5,
      dribble: 7,
      defense: 10,
      special: "Perfect Tackle",
      unlocked: false,
    },
    {
      id: "josko-gvardiol",
      name: "Josko Gvardiol",
      rarity: "Legendary",
      speed: 8,
      shot: 6,
      dribble: 8,
      defense: 9,
      special: "Left-Side Lockdown",
      unlocked: false,
    },
    {
      id: "jurrien-timber",
      name: "Jurrien Timber",
      rarity: "Legendary",
      speed: 8,
      shot: 6,
      dribble: 8,
      defense: 9,
      special: "Quick Recovery",
      unlocked: false,
    },
    {
      id: "zico",
      name: "Zico",
      rarity: "Legendary",
      speed: 8,
      shot: 9,
      dribble: 10,
      defense: 5,
      special: "Golden Playmaker",
      unlocked: false,
    },
    {
      id: "vitinha",
      name: "Vitinha",
      rarity: "Legendary",
      speed: 8,
      shot: 7,
      dribble: 9,
      defense: 7,
      special: "Tempo Touch",
      unlocked: false,
    },
    {
      id: "bruno-fernandes",
      name: "Bruno Fernandes",
      rarity: "Legendary",
      speed: 8,
      shot: 9,
      dribble: 9,
      defense: 7,
      special: "Captain Creator",
      unlocked: false,
    },
    {
      id: "robert-lewandowski",
      name: "Robert Lewandowski",
      rarity: "Legendary",
      speed: 7,
      shot: 10,
      dribble: 8,
      defense: 5,
      special: "Box Assassin",
      unlocked: false,
    },
    {
      id: "michael-olise",
      name: "Michael Olise",
      rarity: "Legendary",
      speed: 9,
      shot: 9,
      dribble: 10,
      defense: 4,
      special: "Silky Wing Cut",
      unlocked: false,
    },
    {
      id: "johan-cruyff",
      name: "Johan Cruyff",
      rarity: "Legendary",
      speed: 9,
      shot: 9,
      dribble: 10,
      defense: 5,
      special: "Total Football Turn",
      unlocked: false,
    },
    {
      id: "thierry-henry",
      name: "Thierry Henry",
      rarity: "Legendary",
      speed: 9,
      shot: 10,
      dribble: 9,
      defense: 4,
      special: "Va-Va-Voom Finish",
      unlocked: false,
    },
    {
      id: "andrea-pirlo",
      name: "Andrea Pirlo",
      rarity: "Legendary",
      speed: 6,
      shot: 8,
      dribble: 9,
      defense: 7,
      special: "Deep Maestro",
      unlocked: false,
    },
    {
      id: "roberto-carlos",
      name: "Roberto Carlos",
      rarity: "Legendary",
      speed: 10,
      shot: 9,
      dribble: 8,
      defense: 8,
      special: "Banana Free Kick",
      unlocked: false,
    },
    {
      id: "cafu",
      name: "Cafu",
      rarity: "Legendary",
      speed: 9,
      shot: 6,
      dribble: 8,
      defense: 9,
      special: "Endless Overlap",
      unlocked: false,
    },
    {
      id: "xavi",
      name: "Xavi",
      rarity: "Legendary",
      speed: 7,
      shot: 7,
      dribble: 10,
      defense: 7,
      special: "Passing Metronome",
      unlocked: false,
    },
    {
      id: "andres-iniesta",
      name: "Andres Iniesta",
      rarity: "Legendary",
      speed: 8,
      shot: 8,
      dribble: 10,
      defense: 6,
      special: "La Croqueta",
      unlocked: false,
    },
    {
      id: "lev-yashin",
      name: "Lev Yashin",
      rarity: "Legendary",
      speed: 5,
      shot: 2,
      dribble: 5,
      defense: 10,
      special: "Black Spider Save",
      unlocked: false,
    },
    {
      id: "carles-puyol",
      name: "Carles Puyol",
      rarity: "Legendary",
      speed: 7,
      shot: 5,
      dribble: 7,
      defense: 10,
      special: "Captain's Last-Ditch Tackle",
      unlocked: false,
    },
    {
      id: "erling-haaland",
      name: "Erling Haaland",
      rarity: "Legendary",
      speed: 9,
      shot: 10,
      dribble: 8,
      defense: 5,
      special: "Power Finish",
      unlocked: false,
    },
    {
      id: "kevin-de-bruyne",
      name: "Kevin De Bruyne",
      rarity: "Legendary",
      speed: 8,
      shot: 9,
      dribble: 9,
      defense: 7,
      special: "Laser Through Ball",
      unlocked: false,
    },
    {
      id: "mohamed-salah",
      name: "Mohamed Salah",
      rarity: "Legendary",
      speed: 10,
      shot: 9,
      dribble: 9,
      defense: 4,
      special: "Curling Cut-In",
      unlocked: false,
    },
    {
      id: "rodri",
      name: "Rodri",
      rarity: "Legendary",
      speed: 7,
      shot: 8,
      dribble: 8,
      defense: 9,
      special: "Control Tower",
      unlocked: false,
    },
    {
      id: "manuel-neuer",
      name: "Manuel Neuer",
      rarity: "Legendary",
      speed: 6,
      shot: 2,
      dribble: 6,
      defense: 10,
      special: "Sweeper Keeper",
      unlocked: false,
    },
    {
      id: "dani-alves",
      name: "Dani Alves",
      rarity: "Legendary",
      speed: 9,
      shot: 7,
      dribble: 9,
      defense: 8,
      special: "Brazilian Overlap",
      unlocked: false,
    },
    {
      id: "marcelo",
      name: "Marcelo",
      rarity: "Legendary",
      speed: 8,
      shot: 7,
      dribble: 10,
      defense: 7,
      special: "Flair Fullback",
      unlocked: false,
    },
  ];

  const cardDetails = {
    "ali-dia": {
      grade: 46,
      position: "ST",
      cardSource: "Beginner Draft user-supplied rating",
      draft: "Beginner Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#64748b",
        accent: "#cbd5e1",
        background: "#e2e8f0",
        hairStyle: "side-part",
      },
    },
    "massimo-taibi": {
      grade: 49,
      position: "G",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#d7a57f",
        hair: "#2f241d",
        shirt: "#16a34a",
        accent: "#ffffff",
        background: "#dcfce7",
        hairStyle: "classic",
      },
    },
    bebeto: {
      grade: 50,
      position: "RB",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#a66a48",
        hair: "#5a3824",
        shirt: "#fde047",
        accent: "#22c55e",
        background: "#fef9c3",
        hairStyle: "curly",
      },
    },
    "julien-faubert": {
      grade: 50,
      position: "RW",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#d8a078",
        hair: "#24180f",
        shirt: "#ffffff",
        accent: "#7c3aed",
        background: "#f5f3ff",
        hairStyle: "short",
      },
    },
    "joey-beauchamp": {
      grade: 50,
      position: "LW",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#d19a74",
        hair: "#3b2a1d",
        shirt: "#38bdf8",
        accent: "#ffffff",
        background: "#e0f2fe",
        hairStyle: "flat",
      },
    },
    "winston-bogarde": {
      grade: 52,
      position: "CB",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#2563eb",
        accent: "#ffffff",
        background: "#dbeafe",
        hairStyle: "buzz",
      },
    },
    "harry-maguire": {
      grade: 53,
      position: "CB",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#d8a078",
        hair: "#7c4a2d",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "side-part",
      },
    },
    "joe-willock": {
      grade: 54,
      position: "CAM",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#7f5139",
        hair: "#101010",
        shirt: "#0f172a",
        accent: "#ffffff",
        background: "#e5e7eb",
        hairStyle: "tight-curls",
      },
    },
    "tomas-brolin": {
      grade: 51,
      position: "CM",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#d7a57f",
        hair: "#c07a3d",
        shirt: "#facc15",
        accent: "#2563eb",
        background: "#fef3c7",
        hairStyle: "classic",
      },
    },
    "alberto-moreno": {
      grade: 52,
      position: "LB",
      cardSource: "Beginner Draft inferred rating; user-supplied position",
      draft: "Beginner Draft",
      portrait: {
        skin: "#c9855c",
        hair: "#2d2118",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "messy",
      },
    },
    "loris-karius": {
      grade: 50,
      position: "G",
      cardSource: "Beginner Draft user-supplied rating",
      draft: "Beginner Draft",
      portrait: {
        skin: "#d7a57f",
        hair: "#2a2018",
        shirt: "#84cc16",
        accent: "#111827",
        background: "#ecfccb",
        hairStyle: "short",
      },
    },
    "titus-bramble": {
      grade: 51,
      position: "CB",
      cardSource: "Beginner Draft user-supplied rating",
      draft: "Beginner Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#2563eb",
        accent: "#ffffff",
        background: "#dbeafe",
        hairStyle: "buzz",
      },
    },
    "andre-santos": {
      grade: 50,
      position: "LB",
      cardSource: "Beginner Draft user-supplied rating",
      draft: "Beginner Draft",
      portrait: {
        skin: "#a66a48",
        hair: "#151515",
        shirt: "#facc15",
        accent: "#22c55e",
        background: "#fef9c3",
        hairStyle: "messy",
      },
    },
    bebe: {
      grade: 49,
      position: "RW",
      cardSource: "Beginner Draft user-supplied rating",
      draft: "Beginner Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "short",
      },
    },
    "lionel-messi": {
      grade: 119,
      position: "RW",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#e3ad7d",
        hair: "#4b2e1f",
        shirt: "#facc15",
        accent: "#2563eb",
        background: "#fef3c7",
        hairStyle: "side-part",
        beard: true,
      },
    },
    "lamine-yamal": {
      grade: 119,
      position: "RW",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#9b6546",
        hair: "#151515",
        shirt: "#7c3aed",
        accent: "#ef4444",
        background: "#ede9fe",
        hairStyle: "tight-curls",
      },
    },
    neymar: {
      grade: 108,
      position: "LW",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#c9855c",
        hair: "#f6d365",
        shirt: "#fde047",
        accent: "#22c55e",
        background: "#dcfce7",
        hairStyle: "mohawk",
      },
    },
    "luis-suarez": {
      grade: 105,
      position: "ST",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#d49a71",
        hair: "#2d2118",
        shirt: "#38bdf8",
        accent: "#0f172a",
        background: "#e0f2fe",
        hairStyle: "short",
        beard: true,
      },
    },
    "gareth-bale": {
      grade: 117,
      position: "RW",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#e7b58b",
        hair: "#3f2a1f",
        shirt: "#ffffff",
        accent: "#16a34a",
        background: "#dcfce7",
        hairStyle: "topknot",
      },
    },
    ronaldinho: {
      grade: 117,
      position: "LW",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#121212",
        shirt: "#facc15",
        accent: "#22c55e",
        background: "#fef9c3",
        hairStyle: "headband-curls",
        headband: "#ffffff",
      },
    },
    "diego-maradona": {
      grade: 117,
      position: "RW",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#c9855c",
        hair: "#211814",
        shirt: "#38bdf8",
        accent: "#ffffff",
        background: "#dbeafe",
        hairStyle: "curly",
      },
    },
    "iker-casillas": {
      grade: 116,
      position: "G",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#d6a078",
        hair: "#2a2018",
        shirt: "#16a34a",
        accent: "#ffffff",
        background: "#dcfce7",
        hairStyle: "short",
      },
    },
    "kylian-mbappe": {
      grade: 120,
      position: "LW",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#8c5a3c",
        hair: "#101010",
        shirt: "#2563eb",
        accent: "#ef4444",
        background: "#dbeafe",
        hairStyle: "buzz",
      },
    },
    "gianluigi-buffon": {
      grade: 117,
      position: "G",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#d7a57f",
        hair: "#2f241d",
        shirt: "#facc15",
        accent: "#111827",
        background: "#fef3c7",
        hairStyle: "side-part",
        beard: true,
      },
    },
    "vinicius-junior": {
      grade: 117,
      position: "LW",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#7d5038",
        hair: "#101010",
        shirt: "#ffffff",
        accent: "#7c3aed",
        background: "#ede9fe",
        hairStyle: "messy",
      },
    },
    "cristiano-ronaldo": {
      grade: 117,
      position: "LW",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#d39b71",
        hair: "#1f1712",
        shirt: "#ef4444",
        accent: "#16a34a",
        background: "#dcfce7",
        hairStyle: "classic",
      },
    },
    "david-raya": {
      grade: 117,
      position: "G",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#c88f66",
        hair: "#1f1712",
        shirt: "#84cc16",
        accent: "#111827",
        background: "#ecfccb",
        hairStyle: "short",
        beard: true,
      },
    },
    "joan-garcia": {
      grade: 117,
      position: "G",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#d19a74",
        hair: "#2a2018",
        shirt: "#22c55e",
        accent: "#ffffff",
        background: "#dcfce7",
        hairStyle: "flat",
      },
    },
    pele: {
      grade: 117,
      position: "ST",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#7f5139",
        hair: "#111111",
        shirt: "#facc15",
        accent: "#16a34a",
        background: "#fef9c3",
        hairStyle: "short",
      },
    },
    "franz-beckenbauer": {
      grade: 117,
      position: "CB",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#dfaf86",
        hair: "#d1a15f",
        shirt: "#ffffff",
        accent: "#111827",
        background: "#e0f2fe",
        hairStyle: "classic",
      },
    },
    "jamie-carragher": {
      grade: 103,
      position: "CB",
      cardSource: "Pro Draft inferred rating; user-supplied position",
      draft: "Pro Draft",
      portrait: {
        skin: "#d8a078",
        hair: "#3b2a1d",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "short",
      },
    },
    pedri: {
      grade: 119,
      position: "CM",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#d49a71",
        hair: "#24180f",
        shirt: "#7c3aed",
        accent: "#ef4444",
        background: "#ede9fe",
        hairStyle: "messy",
      },
    },
    "jude-bellingham": {
      grade: 116,
      position: "CM",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#ffffff",
        accent: "#7c3aed",
        background: "#f5f3ff",
        hairStyle: "tight-curls",
      },
    },
    "luis-figo": {
      grade: 117,
      position: "CAM",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#d09a73",
        hair: "#2a2018",
        shirt: "#2563eb",
        accent: "#f8fafc",
        background: "#dbeafe",
        hairStyle: "classic",
      },
    },
    "harry-kane": {
      grade: 117,
      position: "ST",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#dfad83",
        hair: "#c07a3d",
        shirt: "#ffffff",
        accent: "#0f172a",
        background: "#f8fafc",
        hairStyle: "side-part",
        beard: true,
      },
    },
    "luka-modric": {
      grade: 119,
      position: "CM",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#d7a177",
        hair: "#b77945",
        shirt: "#ffffff",
        accent: "#7c3aed",
        background: "#f5f3ff",
        hairStyle: "classic",
      },
    },
    "virgil-van-dijk": {
      grade: 117,
      position: "CB",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#8b5a3c",
        hair: "#101010",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "topknot",
        beard: true,
      },
    },
    "achraf-hakimi": {
      grade: 117,
      position: "RB",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#a66a48",
        hair: "#101010",
        shirt: "#2563eb",
        accent: "#ef4444",
        background: "#dbeafe",
        hairStyle: "short",
      },
    },
    "alphonso-davies": {
      grade: 116,
      position: "LB",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#704832",
        hair: "#0f0f0f",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "buzz",
      },
    },
    "declan-rice": {
      grade: 117,
      position: "CM",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#d8a078",
        hair: "#5c3a24",
        shirt: "#ef4444",
        accent: "#f8fafc",
        background: "#fee2e2",
        hairStyle: "side-part",
      },
    },
    "sergio-ramos": {
      grade: 117,
      position: "CB",
      cardSource: "Spooky Draft user-supplied rating",
      draft: "Spooky Draft",
      portrait: {
        skin: "#d6a078",
        hair: "#2a2018",
        shirt: "#ffffff",
        accent: "#111827",
        background: "#e5e7eb",
        hairStyle: "classic",
        beard: true,
      },
    },
    "rio-ferdinand": {
      grade: 117,
      position: "CB",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "buzz",
      },
    },
    "reece-james": {
      grade: 115,
      position: "RB",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#7f5139",
        hair: "#101010",
        shirt: "#2563eb",
        accent: "#ffffff",
        background: "#dbeafe",
        hairStyle: "short",
      },
    },
    william: {
      grade: 117,
      position: "LW",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#a66a48",
        hair: "#141414",
        shirt: "#fde047",
        accent: "#22c55e",
        background: "#fef9c3",
        hairStyle: "curly",
      },
    },
    "zinedine-zidane": {
      grade: 117,
      position: "CAM",
      cardSource: "Ramadan Draft user-supplied rating",
      draft: "Ramadan Draft",
      portrait: {
        skin: "#d19a74",
        hair: "#1f1712",
        shirt: "#ffffff",
        accent: "#7c3aed",
        background: "#f5f3ff",
        hairStyle: "buzz",
      },
    },
    "federico-dimarco": {
      grade: 119,
      position: "CB",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#d19a74",
        hair: "#2a2018",
        shirt: "#2563eb",
        accent: "#111827",
        background: "#dbeafe",
        hairStyle: "classic",
        beard: true,
      },
    },
    "paolo-maldini": {
      grade: 117,
      position: "CB",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#d8a078",
        hair: "#3b2a1d",
        shirt: "#ef4444",
        accent: "#111827",
        background: "#fee2e2",
        hairStyle: "classic",
      },
    },
    "josko-gvardiol": {
      grade: 116,
      position: "LB",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#d7a57f",
        hair: "#7c4a2d",
        shirt: "#38bdf8",
        accent: "#ffffff",
        background: "#e0f2fe",
        hairStyle: "short",
      },
    },
    "jurrien-timber": {
      grade: 117,
      position: "RB",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "tight-curls",
      },
    },
    zico: {
      grade: 117,
      position: "CAM",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#b77955",
        hair: "#2d2118",
        shirt: "#facc15",
        accent: "#22c55e",
        background: "#fef9c3",
        hairStyle: "curly",
      },
    },
    vitinha: {
      grade: 117,
      position: "CM",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#d09a73",
        hair: "#2a2018",
        shirt: "#2563eb",
        accent: "#ef4444",
        background: "#dbeafe",
        hairStyle: "messy",
      },
    },
    "bruno-fernandes": {
      grade: 120,
      position: "CM",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#d49a71",
        hair: "#2d2118",
        shirt: "#ef4444",
        accent: "#111827",
        background: "#fee2e2",
        hairStyle: "side-part",
        beard: true,
      },
    },
    "robert-lewandowski": {
      grade: 117,
      position: "ST",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#d7a57f",
        hair: "#4b2e1f",
        shirt: "#7c3aed",
        accent: "#ef4444",
        background: "#ede9fe",
        hairStyle: "classic",
      },
    },
    "michael-olise": {
      grade: 120,
      position: "RW",
      cardSource: "Legendary Draft user-supplied rating",
      draft: "Legendary Draft",
      portrait: {
        skin: "#8c5a3c",
        hair: "#101010",
        shirt: "#ef4444",
        accent: "#2563eb",
        background: "#fee2e2",
        hairStyle: "tight-curls",
      },
    },
    "johan-cruyff": {
      grade: 117,
      position: "CAM",
      cardSource: "Pro Draft inferred rating and position",
      draft: "Pro Draft",
      portrait: {
        skin: "#d7a57f",
        hair: "#c07a3d",
        shirt: "#f97316",
        accent: "#ffffff",
        background: "#ffedd5",
        hairStyle: "classic",
      },
    },
    "thierry-henry": {
      grade: 117,
      position: "ST",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "buzz",
      },
    },
    "andrea-pirlo": {
      grade: 117,
      position: "CM",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#d8a078",
        hair: "#3b2a1d",
        shirt: "#ffffff",
        accent: "#111827",
        background: "#e5e7eb",
        hairStyle: "classic",
        beard: true,
      },
    },
    "roberto-carlos": {
      grade: 117,
      position: "LB",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#facc15",
        accent: "#22c55e",
        background: "#fef9c3",
        hairStyle: "buzz",
      },
    },
    cafu: {
      grade: 117,
      position: "RB",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#facc15",
        accent: "#22c55e",
        background: "#fef9c3",
        hairStyle: "short",
      },
    },
    xavi: {
      grade: 117,
      position: "CM",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#d6a078",
        hair: "#2a2018",
        shirt: "#7c3aed",
        accent: "#ef4444",
        background: "#ede9fe",
        hairStyle: "short",
      },
    },
    "andres-iniesta": {
      grade: 117,
      position: "CAM",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#d8a078",
        hair: "#2a2018",
        shirt: "#7c3aed",
        accent: "#ef4444",
        background: "#ede9fe",
        hairStyle: "buzz",
      },
    },
    "lev-yashin": {
      grade: 117,
      position: "G",
      cardSource: "Pro Draft user-supplied rating",
      draft: "Pro Draft",
      portrait: {
        skin: "#d6a078",
        hair: "#111111",
        shirt: "#111827",
        accent: "#ffffff",
        background: "#e5e7eb",
        hairStyle: "flat",
      },
    },
    "carles-puyol": {
      grade: 117,
      position: "CB",
      cardSource: "Pro Draft inferred rating and position",
      draft: "Pro Draft",
      portrait: {
        skin: "#d49a71",
        hair: "#3b2a1d",
        shirt: "#7c3aed",
        accent: "#ef4444",
        background: "#ede9fe",
        hairStyle: "curly",
      },
    },
    "erling-haaland": {
      grade: 120,
      position: "ST",
      cardSource: "Elite Draft user-supplied rating",
      draft: "Elite Draft",
      portrait: {
        skin: "#dfaf86",
        hair: "#d1a15f",
        shirt: "#38bdf8",
        accent: "#ffffff",
        background: "#e0f2fe",
        hairStyle: "side-part",
      },
    },
    "kevin-de-bruyne": {
      grade: 120,
      position: "CM",
      cardSource: "Elite Draft user-supplied rating",
      draft: "Elite Draft",
      portrait: {
        skin: "#d8a078",
        hair: "#c07a3d",
        shirt: "#38bdf8",
        accent: "#ffffff",
        background: "#e0f2fe",
        hairStyle: "messy",
      },
    },
    "mohamed-salah": {
      grade: 119,
      position: "RW",
      cardSource: "Elite Draft user-supplied rating",
      draft: "Elite Draft",
      portrait: {
        skin: "#a66a48",
        hair: "#101010",
        shirt: "#ef4444",
        accent: "#ffffff",
        background: "#fee2e2",
        hairStyle: "curly",
        beard: true,
      },
    },
    rodri: {
      grade: 119,
      position: "CM",
      cardSource: "Elite Draft user-supplied rating",
      draft: "Elite Draft",
      portrait: {
        skin: "#d49a71",
        hair: "#2a2018",
        shirt: "#38bdf8",
        accent: "#ffffff",
        background: "#e0f2fe",
        hairStyle: "classic",
      },
    },
    "manuel-neuer": {
      grade: 119,
      position: "G",
      cardSource: "Elite Draft user-supplied rating",
      draft: "Elite Draft",
      portrait: {
        skin: "#d7a57f",
        hair: "#d1a15f",
        shirt: "#16a34a",
        accent: "#ffffff",
        background: "#dcfce7",
        hairStyle: "short",
      },
    },
    "dani-alves": {
      grade: 119,
      position: "RB",
      cardSource: "Elite Draft user-supplied rating",
      draft: "Elite Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#7c3aed",
        accent: "#ef4444",
        background: "#ede9fe",
        hairStyle: "short",
      },
    },
    marcelo: {
      grade: 119,
      position: "LB",
      cardSource: "Elite Draft user-supplied rating",
      draft: "Elite Draft",
      portrait: {
        skin: "#8f5b3c",
        hair: "#101010",
        shirt: "#ffffff",
        accent: "#7c3aed",
        background: "#f5f3ff",
        hairStyle: "curly",
      },
    },
  };

  const playerPhotoUrls = {
    "ali-dia": "https://footballoutcasts.weebly.com/uploads/8/7/3/6/87363432/ali-dia-southampton_orig.jpg",
    "massimo-taibi": "https://wips.plug.it/cips/sport.virgilio.it/cms/2023/02/massimo-taibi-1.jpg?w=1217&a=r",
    bebeto: "https://upload.wikimedia.org/wikipedia/commons/6/68/Bebeto_brazil_%28cropped%29.jpg",
    "julien-faubert": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Faubert0410.JPG/500px-Faubert0410.JPG",
    "joey-beauchamp": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Joey_Beauchamp.png",
    "winston-bogarde": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Winston_bogarde-1507900545.jpg/500px-Winston_bogarde-1507900545.jpg",
    "harry-maguire": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Harry_Maguire_2023_%28cropped%29.jpg/500px-Harry_Maguire_2023_%28cropped%29.jpg",
    "joe-willock": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/1_joe_willock_2018.jpg/500px-1_joe_willock_2018.jpg",
    "tomas-brolin": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Tomas_Brolin.jpg/500px-Tomas_Brolin.jpg",
    "alberto-moreno": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Alberto_Moreno_2017.jpg",
    "loris-karius": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Loris_Karius.jpg/500px-Loris_Karius.jpg",
    "lionel-messi": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Lionel_Messi_NE_Revolution_Inter_Miami_7.9.25-178_%28cropped_2%29.jpg/500px-Lionel_Messi_NE_Revolution_Inter_Miami_7.9.25-178_%28cropped_2%29.jpg",
    "lamine-yamal": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Lamine_Yamal_a_Xina_%282025%29.png/500px-Lamine_Yamal_a_Xina_%282025%29.png",
    neymar: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg/500px-Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg",
    "gareth-bale": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/2022_FIFA_World_Cup_United_States_1%E2%80%931_Wales_-_%2832%29_%28cropped%29.jpg/500px-2022_FIFA_World_Cup_United_States_1%E2%80%931_Wales_-_%2832%29_%28cropped%29.jpg",
    ronaldinho: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/2019_-_Press_conferences_-_Day_1_ENX_6950_%2849019873887%29_%28cropped%29.jpg/500px-2019_-_Press_conferences_-_Day_1_ENX_6950_%2849019873887%29_%28cropped%29.jpg",
    "diego-maradona": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Argentina_celebrando_copa_%28cropped%29.jpg/500px-Argentina_celebrando_copa_%28cropped%29.jpg",
    "vinicius-junior": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg/500px-Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg",
    "cristiano-ronaldo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Cristiano_Ronaldo_2275_%28cropped%29.jpg/500px-Cristiano_Ronaldo_2275_%28cropped%29.jpg",
    pele: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Pele_con_brasil_%28cropped%29.jpg/500px-Pele_con_brasil_%28cropped%29.jpg",
    "franz-beckenbauer": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Franz_Beckenbauer_%281975%29.jpg/500px-Franz_Beckenbauer_%281975%29.jpg",
    "jude-bellingham": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg/500px-Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg",
    "harry-kane": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Harry_Kane_England_v_Ghana_23_June_2026-219.jpg/500px-Harry_Kane_England_v_Ghana_23_June_2026-219.jpg",
    "luka-modric": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Ofrenda_de_la_Liga_y_la_Champions-57-L.Mill%C3%A1n_%2852109310843%29_%28Luka_Modri%C4%87%29.jpg/500px-Ofrenda_de_la_Liga_y_la_Champions-57-L.Mill%C3%A1n_%2852109310843%29_%28Luka_Modri%C4%87%29.jpg",
    "virgil-van-dijk": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/20160604_AUT_NED_8876_%28cropped%29.jpg/500px-20160604_AUT_NED_8876_%28cropped%29.jpg",
    "achraf-hakimi": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg/500px-Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg",
    "bruno-fernandes": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bruno_Fernandes_USMNT_v_Portugal_Mar_31_2026-27_%28cropped%29.jpg/500px-Bruno_Fernandes_USMNT_v_Portugal_Mar_31_2026-27_%28cropped%29.jpg",
    "robert-lewandowski": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg/500px-2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg",
    "michael-olise": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Michael_Olise_France_v_Senegal_16_June_2026-307_%28cropped%29.jpg/500px-Michael_Olise_France_v_Senegal_16_June_2026-307_%28cropped%29.jpg",
    cafu: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cafu_-_26.02.2026_-_Cerim%C3%B4nia_de_apresenta%C3%A7%C3%A3o_das_ta%C3%A7as_da_Copa_do_Mundo_de_2026.jpg/500px-Cafu_-_26.02.2026_-_Cerim%C3%B4nia_de_apresenta%C3%A7%C3%A3o_das_ta%C3%A7as_da_Copa_do_Mundo_de_2026.jpg",
    "erling-haaland": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg/500px-Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg",
    rodri: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/RODRI_-_SWE_vs_ESP_-_UEFA_EURO_2020_QUALIFIERS_-_2019.10.15_%28cropped%29.jpg/500px-RODRI_-_SWE_vs_ESP_-_UEFA_EURO_2020_QUALIFIERS_-_2019.10.15_%28cropped%29.jpg",
    "titus-bramble": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Titus_Bramble_2011.jpg/1280px-Titus_Bramble_2011.jpg",
    "luis-suarez": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Luis_Su%C3%A1rez_2026_%28cropped%29.jpg",
    "iker-casillas": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Iker-Casillas-SportsTrade-2021-cropped.jpg/1280px-Iker-Casillas-SportsTrade-2021-cropped.jpg",
    "kylian-mbappe": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg/500px-Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg",
    "gianluigi-buffon": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Norway_Italy_-_June_2025_A_44_%28Gianluigi_Buffon%29.jpg/500px-Norway_Italy_-_June_2025_A_44_%28Gianluigi_Buffon%29.jpg",
    "david-raya": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/David_Raya_in_2025_%28cropped%29.jpg/500px-David_Raya_in_2025_%28cropped%29.jpg",
    "joan-garcia": "https://upload.wikimedia.org/wikipedia/commons/4/4b/CE_Manresa_Alev%C3%AD_A%2C_amb_el_porter_Joan_Garcia%2C_abril_de_2012_%28cropped%29.jpg",
    "jamie-carragher": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Football_against_poverty_2014_-_Jamie_Carragher_%28cropped%29.jpg/500px-Football_against_poverty_2014_-_Jamie_Carragher_%28cropped%29.jpg",
    pedri: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Pedri.jpg/500px-Pedri.jpg",
    "luis-figo": "https://upload.wikimedia.org/wikipedia/commons/1/15/Luis_Figo_2023.jpg",
    "alphonso-davies": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Alphonso_Davies_Canada_v_Qatar_18_June_2026-007_%28cropped%29.jpg/500px-Alphonso_Davies_Canada_v_Qatar_18_June_2026-007_%28cropped%29.jpg",
    "declan-rice": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Declan_Rice_England_v_Ghana_23_June_2026-150.jpg/500px-Declan_Rice_England_v_Ghana_23_June_2026-150.jpg",
    "sergio-ramos": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Sergio_Ramos_Interview_2021_%28cropped%29.jpg",
    "rio-ferdinand": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Web_Summit_2015_-_Dublin%2C_Ireland_-_22183056474_%28cropped%29.jpg/500px-Web_Summit_2015_-_Dublin%2C_Ireland_-_22183056474_%28cropped%29.jpg",
    "reece-james": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Reece_James_England_v_Ghana_23_June_2026-248_%28cropped%29.jpg/500px-Reece_James_England_v_Ghana_23_June_2026-248_%28cropped%29.jpg",
    william: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/William_de_Asevedo_Furtado_-_Rio_2016.jpg/500px-William_de_Asevedo_Furtado_-_Rio_2016.jpg",
    "zinedine-zidane": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg",
    "federico-dimarco": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Norway_Italy_-_June_2025_A_26_%28cropped%29.jpg/500px-Norway_Italy_-_June_2025_A_26_%28cropped%29.jpg",
    "paolo-maldini": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Paolo_Maldini_AC_Milan_Technical_director_2018.jpg",
    "josko-gvardiol": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2611_%28Jo%C5%A1ko_Gvardiol%29.jpg/1280px-2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2611_%28Jo%C5%A1ko_Gvardiol%29.jpg",
    "jurrien-timber": "https://upload.wikimedia.org/wikipedia/commons/9/9f/JURRIEN_TIMBER.jpg",
    vitinha: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Vitinha_USMNT_v_Portugal_Mar_31_2026-50_%28cropped%29.jpg/500px-Vitinha_USMNT_v_Portugal_Mar_31_2026-50_%28cropped%29.jpg",
    "johan-cruyff": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Johan_Cruijff_%281974%29.jpg/500px-Johan_Cruijff_%281974%29.jpg",
    "thierry-henry": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Thierry_Henry_%2851649035951%29_%28cropped%29.jpg/500px-Thierry_Henry_%2851649035951%29_%28cropped%29.jpg",
    "andrea-pirlo": "https://upload.wikimedia.org/wikipedia/commons/6/6e/20150616_-_Portugal_-_Italie_-_Gen%C3%A8ve_-_Andrea_Pirlo_%28cropped%29.jpg",
    "roberto-carlos": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/LS3_1288_%2853332367864%29_%28cropped%29.jpg/500px-LS3_1288_%2853332367864%29_%28cropped%29.jpg",
    "andres-iniesta": "https://upload.wikimedia.org/wikipedia/commons/5/57/Andr%C3%A9s_Iniesta_2019.jpg",
    "lev-yashin": "https://upload.wikimedia.org/wikipedia/commons/f/f5/LevYashin.JPG",
    "carles-puyol": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Premios_Goya_2020_-_Carles_Pujol.jpg/500px-Premios_Goya_2020_-_Carles_Pujol.jpg",
    "kevin-de-bruyne": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/500px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg",
    "mohamed-salah": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mohamed_Salah_2018.jpg",
    "manuel-neuer": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/20180602_FIFA_Friendly_Match_Austria_vs._Germany_Manuel_Neuer_850_0723.jpg/500px-20180602_FIFA_Friendly_Match_Austria_vs._Germany_Manuel_Neuer_850_0723.jpg",
    "dani-alves": "https://upload.wikimedia.org/wikipedia/commons/d/dd/07_07_2019_Final_da_Copa_Am%C3%A9rica_2019_%2848226649586%29_%28cropped%29.jpg",
    marcelo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Marcelo_Vieira_in_2022.jpg/500px-Marcelo_Vieira_in_2022.jpg",
    "andre-santos": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Andre_Santos_2.jpg",
    bebe: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Tiago_Manuel_Dias_Correia.JPG/500px-Tiago_Manuel_Dias_Correia.JPG",
    zico: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Zico_2012_3.jpg/500px-Zico_2012_3.jpg",
    xavi: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Xavi%2C_Persepolis_vs._Al_Sadd%2C_20190520_02_%28cropped%29.jpg",
  };

  for (const player of [...starterPlayers, ...legendCards]) {
    Object.assign(player, cardDetails[player.id]);
    if (playerPhotoUrls[player.id]) {
      player.photoUrl = playerPhotoUrls[player.id];
    }
  }

  const allPlayers = [...starterPlayers, ...legendCards];
  const draftOrder = ["Beginner Draft", "Pro Draft", "Spooky Draft", "Ramadan Draft", "Legendary Draft", "Elite Draft"];
  const drafts = draftOrder.map((name) => ({
    name,
    ids: allPlayers.filter((player) => player.draft === name).map((player) => player.id),
  }));
  const packTypes = [
    {
      id: "target-draft",
      name: "Target Draft Pack",
      cost: 100,
      description: "Pulls from your selected draft.",
      kind: "draft",
    },
    {
      id: "elite-draft",
      name: "Elite Draft Pack",
      cost: 180,
      description: "A premium shot at the Elite Draft.",
      kind: "fixed-draft",
      draft: "Elite Draft",
    },
    {
      id: "special",
      name: "Special Pack",
      cost: 150,
      description: "Unlocks clubs, teams, and special edition cards.",
      kind: "special",
    },
  ];
  const specialCards = [
    {
      id: "club-barcelona",
      name: "FC Barcelona",
      type: "Club",
      rarity: "Special",
      bonus: "Possession boost",
      draft: "Special Cards",
    },
    {
      id: "club-real-madrid",
      name: "Real Madrid",
      type: "Club",
      rarity: "Special",
      bonus: "Clutch finishing",
      draft: "Special Cards",
    },
    {
      id: "team-brazil-2002",
      name: "Brazil 2002",
      type: "Team",
      rarity: "Special",
      bonus: "Attack flair",
      draft: "Special Cards",
    },
    {
      id: "team-argentina-1986",
      name: "Argentina 1986",
      type: "Team",
      rarity: "Special",
      bonus: "Solo dribble",
      draft: "Special Cards",
    },
    {
      id: "special-ballon-dor",
      name: "Ballon d'Or Shine",
      type: "Special Player Card",
      rarity: "Special",
      bonus: "Legend card glow",
      draft: "Special Cards",
    },
  ];

  window.GAME_DATA = {
    starterPlayers,
    legendCards,
    allPlayers,
    drafts,
    draftOrder,
    packTypes,
    specialCards,
    starterIds: starterPlayers.map((player) => player.id),
    legendIds: legendCards.map((player) => player.id),
    getPlayerById(id) {
      return allPlayers.find((player) => player.id === id) || starterPlayers[0];
    },
    getDraftByName(name) {
      return drafts.find((draft) => draft.name === name) || drafts[0];
    },
    getPackTypeById(id) {
      return packTypes.find((packType) => packType.id === id) || packTypes[0];
    },
    getSpecialCardById(id) {
      return specialCards.find((card) => card.id === id) || specialCards[0];
    },
  };
})();
